# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import exec_actions_pb2 as exec__actions__pb2


class ExecActionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAction = channel.unary_stream(
                '/ExecAction/RunAction',
                request_serializer=exec__actions__pb2.ActionList.SerializeToString,
                response_deserializer=exec__actions__pb2.ActionStatus.FromString,
                )


class ExecActionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecActionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAction': grpc.unary_stream_rpc_method_handler(
                    servicer.RunAction,
                    request_deserializer=exec__actions__pb2.ActionList.FromString,
                    response_serializer=exec__actions__pb2.ActionStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExecAction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExecAction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ExecAction/RunAction',
            exec__actions__pb2.ActionList.SerializeToString,
            exec__actions__pb2.ActionStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
