# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exec_actions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65xec_actions.proto\"5\n\nActionList\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x18\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x07.Action\"%\n\x06\x41\x63tion\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"E\n\x0c\x41\x63tionStatus\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrent_step\x18\x02 \x01(\x05\x12\x13\n\x0btotal_steps\x18\x03 \x01(\x05\x32\x39\n\nExecAction\x12+\n\tRunAction\x12\x0b.ActionList\x1a\r.ActionStatus\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exec_actions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACTIONLIST']._serialized_start=22
  _globals['_ACTIONLIST']._serialized_end=75
  _globals['_ACTION']._serialized_start=77
  _globals['_ACTION']._serialized_end=114
  _globals['_ACTIONSTATUS']._serialized_start=116
  _globals['_ACTIONSTATUS']._serialized_end=185
  _globals['_EXECACTION']._serialized_start=187
  _globals['_EXECACTION']._serialized_end=244
# @@protoc_insertion_point(module_scope)
